import React from 'react'
import type { VisualizationMeta } from '../types'

const registry: VisualizationMeta[] = [
  {
    id: 'electric-charge',
    topic: 'Electrostatics',
    title: "Coulomb's Law & Electric Charge",
    conceptTags: ['coulombs-law', 'charge', 'force', 'inverse-square'],
    difficultyLevel: 1,
    commonMisconceptions: [
      'Force only acts on one charge, not both',
      'Force increases with distance',
    ],
    recommendedUseCases: ['Intro lecture', 'Lab pre-work'],
    caption: {
      what: 'Two point charges interact via Coulomb\'s Law: F = kq₁q₂/r².',
      why: 'Understanding the inverse-square relationship builds intuition for all field phenomena.',
      notice: 'As distance halves, force quadruples. Opposite charges attract; like charges repel.',
    },
    component: React.lazy(() => import('./ElectricCharge/index')),
  },
  {
    id: 'electric-field',
    topic: 'Electrostatics',
    title: 'Electric Field Mapping',
    conceptTags: ['electric-field', 'field-lines', 'superposition', 'point-charge'],
    difficultyLevel: 2,
    commonMisconceptions: [
      'Field lines represent particle paths',
      'Field strength is uniform between charges',
    ],
    recommendedUseCases: ['Lecture demo', 'Concept exploration'],
    caption: {
      what: 'The electric field is a vector quantity showing force per unit positive charge at every point.',
      why: 'Field visualization reveals superposition and symmetry before solving equations.',
      notice: 'Field lines never cross. Density of lines indicates field strength.',
    },
    component: React.lazy(() => import('./ElectricField/index')),
  },
  {
    id: 'electric-flux',
    topic: 'Electrostatics',
    title: 'Electric Flux',
    conceptTags: ['flux', 'surface-integral', 'angle', 'field-lines'],
    difficultyLevel: 2,
    commonMisconceptions: [
      'Flux depends on field magnitude only, not orientation',
      'Tilting the surface increases flux',
    ],
    recommendedUseCases: ['Pre-Gauss\'s Law introduction', 'Conceptual quiz prep'],
    caption: {
      what: 'Electric flux Φ = E·A·cos(θ) measures how many field lines pass through a surface.',
      why: 'Flux is the bridge between field geometry and enclosed charge in Gauss\'s Law.',
      notice: 'At θ = 90° the surface is parallel to the field and flux is zero.',
    },
    component: React.lazy(() => import('./ElectricFlux')),
  },
  {
    id: 'gauss-law',
    topic: 'Electrostatics',
    title: "Gauss's Law",
    conceptTags: ['gauss-law', 'gaussian-surface', 'symmetry', 'enclosed-charge'],
    difficultyLevel: 3,
    commonMisconceptions: [
      'Any surface can simplify Gauss\'s Law',
      'Flux through a surface depends on charges outside it',
    ],
    recommendedUseCases: ['Symmetry argument lecture', 'Problem-solving strategy'],
    caption: {
      what: 'Total flux through any closed surface equals Q_enc / ε₀.',
      why: 'Symmetric Gaussian surfaces turn a hard integral into simple algebra.',
      notice: 'Only the charge inside the surface determines the total flux.',
    },
    component: React.lazy(() => import('./GaussLaw')),
  },
  {
    id: 'electric-potential',
    topic: 'Electrostatics',
    title: 'Electric Potential',
    conceptTags: ['electric-potential', 'equipotential', 'gradient', 'voltage'],
    difficultyLevel: 2,
    commonMisconceptions: [
      'High voltage means high field strength everywhere',
      'Equipotential lines are parallel to field lines',
    ],
    recommendedUseCases: ['Energy and field connection lecture', 'Circuit intro'],
    caption: {
      what: 'Electric potential V is potential energy per unit charge; E = -∇V.',
      why: 'Potential is a scalar — easier to add than vector fields.',
      notice: 'E-field always points from high to low potential, perpendicular to equipotentials.',
    },
    component: React.lazy(() => import('./ElectricPotential')),
  },
  {
    id: 'potential-energy',
    topic: 'Electrostatics',
    title: 'Electric Potential Energy',
    conceptTags: ['potential-energy', 'work', 'conservative-force', 'configuration'],
    difficultyLevel: 2,
    commonMisconceptions: [
      'Moving opposite charges apart requires no work',
      'Potential energy and potential are the same thing',
    ],
    recommendedUseCases: ['Work-energy theorem extension', 'Atomic physics motivation'],
    caption: {
      what: 'U = kq₁q₂/r is the energy stored in a two-charge configuration.',
      why: 'Understanding PE explains why charges accelerate and where energy comes from.',
      notice: 'When the field does positive work, PE decreases and KE increases.',
    },
    component: React.lazy(() => import('./PotentialEnergy')),
  },
  {
    id: 'capacitors',
    topic: 'Electrostatics',
    title: 'Capacitors & Dielectrics',
    conceptTags: ['capacitance', 'dielectric', 'parallel-plates', 'energy-storage'],
    difficultyLevel: 2,
    commonMisconceptions: [
      'Inserting a dielectric increases the field',
      'Capacitance depends on voltage',
    ],
    recommendedUseCases: ['Circuit elements intro', 'Lab companion'],
    caption: {
      what: 'C = κε₀A/d relates geometry and material to charge storage capacity.',
      why: 'Capacitors store energy in the electric field between their plates.',
      notice: 'A dielectric reduces the field and increases capacitance for the same voltage.',
    },
    component: React.lazy(() => import('./Capacitors')),
  },
  {
    id: 'current-resistance',
    topic: 'DC Circuits',
    title: 'Current & Resistance',
    conceptTags: ['current', 'resistance', 'ohms-law', 'drift-velocity', 'resistivity'],
    difficultyLevel: 1,
    commonMisconceptions: [
      'Current is consumed by resistors',
      'Electrons move at the speed of light',
    ],
    recommendedUseCases: ['Circuit basics lecture', 'Conceptual intro'],
    caption: {
      what: 'Current I = nqv_d A is the net flow of charge; resistance R = ρL/A opposes it.',
      why: 'Microscopic drift velocity connects macroscopic current to atomic behavior.',
      notice: 'Electrons drift slowly (~mm/s) but the electric signal propagates nearly instantly.',
    },
    component: React.lazy(() => import('./CurrentResistance')),
  },
  {
    id: 'dc-circuits',
    topic: 'DC Circuits',
    title: 'DC Circuits & Kirchhoff\'s Laws',
    conceptTags: ['kirchhoff', 'series', 'parallel', 'voltage-divider', 'current-divider'],
    difficultyLevel: 2,
    commonMisconceptions: [
      'Bulbs in series share voltage equally regardless of resistance',
      'KVL only works for simple loops',
    ],
    recommendedUseCases: ['Circuit analysis lecture', 'Problem-solving practice'],
    caption: {
      what: 'KVL: sum of voltages around any loop = 0. KCL: sum of currents at any node = 0.',
      why: 'These two laws are all you need to analyze any DC network.',
      notice: 'Resistors in parallel share the same voltage; in series they share the same current.',
    },
    component: React.lazy(() => import('./DCCircuits')),
  },
  {
    id: 'magnetic-fields',
    topic: 'Magnetism',
    title: 'Magnetic Fields',
    conceptTags: ['magnetic-field', 'field-lines', 'dipole', 'bar-magnet'],
    difficultyLevel: 1,
    commonMisconceptions: [
      'Magnetic monopoles exist',
      'Magnetic field lines start on north poles',
    ],
    recommendedUseCases: ['Magnetism intro lecture', 'Concept comparison with E-field'],
    caption: {
      what: 'Magnetic field lines form closed loops; B-field is a solenoidal (divergence-free) vector field.',
      why: 'Unlike electric fields, magnetic fields have no sources — ∇·B = 0 always.',
      notice: 'Field lines exit north poles externally but form closed loops inside the magnet.',
    },
    component: React.lazy(() => import('./MagneticFields')),
  },
  {
    id: 'magnetic-force',
    topic: 'Magnetism',
    title: 'Magnetic Force on Charges',
    conceptTags: ['lorentz-force', 'cyclotron', 'cross-product', 'velocity-selector'],
    difficultyLevel: 2,
    commonMisconceptions: [
      'Magnetic force does work on moving charges',
      'A stationary charge feels a magnetic force',
    ],
    recommendedUseCases: ['Lorentz force lecture', 'Particle accelerator motivation'],
    caption: {
      what: 'F = qv × B — the magnetic force is always perpendicular to velocity and does no work.',
      why: 'This perpendicular force causes circular motion: the cyclotron radius r = mv/qB.',
      notice: 'Only moving charges experience magnetic force; the force never changes their speed.',
    },
    component: React.lazy(() => import('./MagneticForce')),
  },
  {
    id: 'biot-savart',
    topic: 'Magnetism',
    title: 'Biot-Savart Law',
    conceptTags: ['biot-savart', 'current-element', 'magnetic-field', 'superposition'],
    difficultyLevel: 3,
    commonMisconceptions: [
      'Field from a wire segment points radially like E-field',
      'The law applies to isolated charge segments',
    ],
    recommendedUseCases: ['Field calculation lecture', 'Loop and wire problems'],
    caption: {
      what: 'dB = (μ₀/4π) I dl × r̂ / r² — each current element contributes a circling field.',
      why: 'Biot-Savart is the magnetic analog of Coulomb\'s Law for building up B from currents.',
      notice: 'The field circles around current; use right-hand rule to find direction.',
    },
    component: React.lazy(() => import('./BiotSavart')),
  },
  {
    id: 'amperes-law',
    topic: 'Magnetism',
    title: "Ampère's Law",
    conceptTags: ['amperes-law', 'amperian-loop', 'enclosed-current', 'symmetry'],
    difficultyLevel: 3,
    commonMisconceptions: [
      'Any loop can simplify Ampère\'s Law',
      'B-field outside a solenoid is significant',
    ],
    recommendedUseCases: ['Symmetric B-field calculation', 'Solenoid and toroid problems'],
    caption: {
      what: '∮ B·dl = μ₀ I_enc — the circulation of B around a closed loop equals μ₀ times enclosed current.',
      why: 'Symmetric Amperian loops reduce hard integrals to simple multiplication.',
      notice: 'Like Gauss\'s Law, Ampère\'s Law is always true but only simplifies with symmetry.',
    },
    component: React.lazy(() => import('./AmperesLaw')),
  },
  {
    id: 'faradays-law',
    topic: 'Induction',
    title: "Faraday's Law of Induction",
    conceptTags: ['faradays-law', 'emf', 'flux', 'lenz-law', 'induction'],
    difficultyLevel: 2,
    commonMisconceptions: [
      'A large B-field always induces a large EMF',
      'Lenz\'s law increases the induced flux',
    ],
    recommendedUseCases: ['Generator/transformer intro', 'EMF calculation'],
    caption: {
      what: 'EMF = -dΦ_B/dt — a changing magnetic flux induces an electromotive force.',
      why: 'Faraday\'s Law is the operating principle of every generator and transformer.',
      notice: 'The negative sign (Lenz\'s Law) means the induced current opposes the flux change.',
    },
    component: React.lazy(() => import('./FaradaysLaw')),
  },
  {
    id: 'inductance',
    topic: 'Induction',
    title: 'Inductance',
    conceptTags: ['inductance', 'solenoid', 'self-induction', 'energy-storage'],
    difficultyLevel: 2,
    commonMisconceptions: [
      'Inductance depends on current magnitude',
      'An inductor opposes DC current indefinitely',
    ],
    recommendedUseCases: ['RL circuit intro', 'Energy storage in magnetic fields'],
    caption: {
      what: 'L = NΦ/I — inductance relates flux linkage to current; V = -L dI/dt.',
      why: 'Inductors store energy in their magnetic field: U = ½LI².',
      notice: 'Inductance only matters when current is changing — steady DC causes no inductive voltage.',
    },
    component: React.lazy(() => import('./Inductance')),
  },
  {
    id: 'rlc-circuits',
    topic: 'AC Circuits',
    title: 'RLC Circuits & Resonance',
    conceptTags: ['rlc', 'resonance', 'impedance', 'phase', 'q-factor'],
    difficultyLevel: 3,
    commonMisconceptions: [
      'Resonance means maximum current always',
      'Capacitors and inductors dissipate power',
    ],
    recommendedUseCases: ['AC circuit analysis', 'Resonance and filters'],
    caption: {
      what: 'At resonance ω₀ = 1/√(LC), impedance is minimized and current is maximized.',
      why: 'RLC resonance underlies radio tuners, filters, and oscillators.',
      notice: 'At resonance the capacitor and inductor voltages cancel, leaving only resistive voltage.',
    },
    component: React.lazy(() => import('./RLCCircuits')),
  },
  {
    id: 'em-waves',
    topic: 'Electromagnetic Waves',
    title: 'Electromagnetic Waves',
    conceptTags: ['em-waves', 'maxwell', 'polarization', 'wave-speed', 'spectrum'],
    difficultyLevel: 3,
    commonMisconceptions: [
      'EM waves need a medium to propagate',
      'E and B fields oscillate in the same direction',
    ],
    recommendedUseCases: ['Maxwell\'s equations capstone', 'Optics bridge'],
    caption: {
      what: 'EM waves are self-sustaining oscillations of E and B, propagating at c = 1/√(μ₀ε₀).',
      why: 'Maxwell\'s synthesis showed light is an electromagnetic wave — unifying optics and E&M.',
      notice: 'E, B, and propagation direction are mutually perpendicular (right-hand rule).',
    },
    component: React.lazy(() => import('./EMWaves')),
  },
]

export default registry
